<?php

namespace AppBundle\Repository;

/**
 * TVShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TVShowRepository extends \Doctrine\ORM\EntityRepository
{
	// ************
	// Question 3 :
	// ____________
	public function findByResearch($query){
		return $this->createQueryBuilder("show")
		->where("show.name LIKE :query")
		->orWhere("show.synopsis LIKE :query")
		->setParameter("query", "%".$query."%")
		->getQuery()
		->getResult();
	}
}
